### PR TITLE
Fixed german translation of pipboy.msg

### PR DESCRIPTION
**Pull request by brussell1**
The german translation of pipboy.msg is incomplete, probably by bad translations in Weblate, when it was still accessible.
This is the fixed version with some minor additional corrections.

### CODE REVIEW

**Comment by burner1024** [comment]
Thanks!

**Comment by burner1024** [comment]
If you could compare and review the file in RPU repo, that would be helpful. I tried applying the patch automatically, it fails due to some mismatches.

**Comment by brussell1** [comment]
Somehow a few lines, that were translated in the UPU file, aren't in the RPU one. That's all. You can copy this one to RPU. Or should I make a new PR?

**Comment by burner1024** [comment]
ok I copied it over

**Pull request merged**
