### PR TITLE
Dialogs test

### PR DESCRIPTION
**Pull request by dzmitry-rudnouski**
Some initial attempt to find inconsistencies between ssl and msg files.

Test result example:

```
Messages in scripts_src/brokhill/hcchad.ssl that missed in data/text/english/dialog/hcchad.msg: 148 149 151 152 153 154 155

Messages in scripts_src/den/dcbilly.ssl that missed in data/text/english/dialog/dcbilly.msg: 202

Messages in scripts_src/den/dcjoey.ssl that missed in data/text/english/dialog/dcjoey.msg: 263 264 265 267 266 268 269 270 271 272 273 274

Messages in scripts_src/gecko/gclenny.ssl that missed in data/text/english/dialog/gclenny.msg: 452 453 460

Messages in scripts_src/klamath/kcardin.ssl that missed in data/text/english/dialog/kcardin.msg: 420 421 422

Messages in scripts_src/klamath/kcsulik.ssl that missed in data/text/english/dialog/kcsulik.msg: 670 700 173 174 175 176 185 186 187 294 295 296 303

Messages in scripts_src/newreno/ncbishop.ssl that missed in data/text/english/dialog/ncbishop.msg: 1820 1840
```

### CODE REVIEW

**Comment by Lexx2k** [comment]
I was confused by the huge amount of missing strings. However, seems a lot of them are false positives, because the procedures are never called for various reasons.

**Comment by burner1024** [comment]
Please keep git history clean when possible, use feature branches or something for pulls.

This is cool but is there any actual bug caught by this test? Manifesting in game, I mean. I checked [first one](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/scripts_src/brokhill/hcchad.ssl#L448), it's just commented out.
Furthermore, if to be used for automatic testing, first all false positives would have to be cleared, and all exceptions marked.

**Comment by dzmitry-rudnouski** [comment]
@burner1024 History cleaned, first 2 false positives removed. Fixed ncliljes as example and can fix others the same way.

**Comment by burner1024** [comment]
So are there any true positives?

**Comment by dzmitry-rudnouski** [comment]
@burner1024, false positives are cleaned. Now test shows true positives only. 1st of them is fixed here: https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/pull/89/commits/404735479455cc7b5c296fd0cd2996cc272fd831

Also I'm checking only 3 functions: Reply, NOption, BOption.
Do other functions work same way (take message from dialog file with the same name) - GOption, display_mstr, floater, any other?

**Comment by burner1024** [comment]
Hm, it does appear to have found some misssing strings after all, which is surprising. Although it's not always clear what to do about those.
`GOption, display_mstr`, etc are macros, not functions. You can review their definitions to see what they do. These 2 in particular take messages from the corresponding file, yes. But other macros can take their strings from elsewhere. And there's various fun stuff like `Reply(122 + dude_is_female + dude_is_mordino)`.

**Comment by Lexx2k** [comment]
Do those nodes crash the game? If there's so many, I wonder why they haven't been reported before.

About the ecnomchf.ssl: Did you test this or do you 100% believe your tool? Removing the dialog option almost certainly will cause issues after leaving the barter mode.

**Comment by dzmitry-rudnouski** [comment]
@Lexx2k, do not crash I suppose. Please advise how to test ecnomchf, it's random encounter.

**Comment by burner1024** [comment]
are you done with this pull or want to continue working on it?

**Comment by dzmitry-rudnouski** [comment]
@burner1024, I'm done for now. Will continue later with other ssl fixing in separate pull request.

**Comment by burner1024** [comment]
OK, please re-raise it against `msg-test` branch, I'd like to make some changes before rolling into master.

**Comment by dzmitry-rudnouski** [comment]
Done.

**Pull request merged**
