### PR TITLE
fix gcbrain crash when PLANT_HAS_PART

### PR DESCRIPTION
**Pull request by dzmitry-rudnouski**
Talk to gcbrain when PLANT_HAS_PART - there is no reply from gcbrain and game crashes after selecting any option:
scr00000
[SLOT08.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/10379462/SLOT08.zip)

Here is fix.

### CODE REVIEW

**Comment by burner1024** [comment]
Need to switch to using proper defines instead of `giq_` and magic numbers.
Why is the `ANKH_GIVEN` condition commented out?
There's no default `Reply` after `Reply(611)`, so either its condition is unnecessary, or a reply would be missing in some cases.

**Comment by dzmitry-rudnouski** [comment]
Corrected.

**Comment by burner1024** [comment]
What about condition?

**Comment by dzmitry-rudnouski** [comment]
ANKH_GIVEN condition is not commented anymore.
Default option after `Reply(611)` is `NOption(233,Node999,004);`

**Comment by dzmitry-rudnouski** [comment]
Yes, you are right, corrected.

**Comment by dzmitry-rudnouski** [comment]
One more crash, now in Node003.
[SLOT09.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/10459919/SLOT09.zip)
Will be fixed in next commits.

**Pull request merged**
